/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.quizms;

import static com.mycompany.quizms.GlobalClass.isAttempted;
import static com.mycompany.quizms.GlobalClass.isAdded;

/**
 *
 * @author tariq
 */


public class SPChooseQuiz extends javax.swing.JFrame {

    /**
     * Creates new form AttemptQuiz
     */
    static int i,indexC;
    public int checkSubject()
    {
        if(SPChooseSubject.subject.equals("ODE"))
        {
            //System.out.println("checkSubject");
            return 0;
        }
        else
        {
           // System.out.println("checkSubject else");
            return 1;
        }
    }
    int isAttempted()
    {
        //int quiz = SPChooseQuiz.i;
        if(isAttempted[Login.index][indexC]==false)
        {
            return 0;
        } 
        else
        {
            return 1;
        }
    }
    public SPChooseQuiz() {
        initComponents();
        switch(SPChooseSubject.subject)
        {
            case "ODE":
                lblQuiz.setText("ODE Quizzes");
                break;
            case "OOP":
                lblQuiz.setText("OOP Quizzes");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBack = new javax.swing.JButton();
        btnQuiz1 = new javax.swing.JButton();
        btnQuiz2 = new javax.swing.JButton();
        btnQuiz3 = new javax.swing.JButton();
        lblStudentsPortal = new javax.swing.JLabel();
        lblQuiz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Portal");

        lblBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBack.setText("Back");
        lblBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBackActionPerformed(evt);
            }
        });

        btnQuiz1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnQuiz1.setText("Quiz 1");
        btnQuiz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuiz1ActionPerformed(evt);
            }
        });

        btnQuiz2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnQuiz2.setText("Quiz 2");
        btnQuiz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuiz2ActionPerformed(evt);
            }
        });

        btnQuiz3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnQuiz3.setText("Quiz 3");
        btnQuiz3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuiz3ActionPerformed(evt);
            }
        });

        lblStudentsPortal.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblStudentsPortal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentsPortal.setText("STUDENT PORTAL");

        lblQuiz.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblQuiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuiz.setText("Quiz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(lblStudentsPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(lblQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(357, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBack)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnQuiz3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnQuiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuiz2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblStudentsPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(btnQuiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuiz2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuiz3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(lblBack)
                .addGap(78, 78, 78))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuiz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuiz2ActionPerformed
        // TODO add your handling code here:
        if(checkSubject()==0)
        {
            i=2;
            indexC=i-1;
            if(isAttempted()==0 && isAdded[SPChooseSubject.sIndexR][indexC]==true)
            {
                SPAttemptQuestion attemptQuestion = new SPAttemptQuestion();
                attemptQuestion.setVisible(true);
                setVisible(false);
            }
            else{
                if(isAttempted()==1)
                {
                    QuizAlreadyAttempted QD = new QuizAlreadyAttempted();
                    QD.setVisible(true);
                    setVisible(false);
                    
                }
                else
                {
                    QuizNotAdded QN = new QuizNotAdded();
                    QN.setVisible(true);
                    setVisible(false);
                    
                    
                } 
             
            }
        }
        else
        {
            i=5;
            indexC=i-1;
            if(isAttempted()==0 && isAdded[SPChooseSubject.sIndexR][indexC]==true)
            {
                SPAttemptQuestion attemptQuestion = new SPAttemptQuestion();
                attemptQuestion.setVisible(true);
                setVisible(false);
            }
            else{
                if(isAttempted()==1)
                {
                    QuizAlreadyAttempted QD = new QuizAlreadyAttempted();
                    QD.setVisible(true);
                    setVisible(false);
                    
                }
                else
                {
                    QuizNotAdded QN = new QuizNotAdded();
                    QN.setVisible(true);
                    setVisible(false);
                    
                    
                } 
             
            }
        }
        /*SPAttemptQuestion attemptQuestion = new SPAttemptQuestion();
        attemptQuestion.setVisible(true);
        setVisible(false);*/
    }//GEN-LAST:event_btnQuiz2ActionPerformed

    private void btnQuiz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuiz1ActionPerformed
        // TODO add your handling code here:
        if(checkSubject()==0)
        {
            //System.out.println("i: "+i);
            i=1;
            indexC=i-1;
            if(isAttempted()==0 && isAdded[SPChooseSubject.sIndexR][indexC]==true)
            {
                SPAttemptQuestion attemptQuestion = new SPAttemptQuestion();
                attemptQuestion.setVisible(true);
                setVisible(false);
            }
            else{
                if(isAttempted()==1)
                {
                    QuizAlreadyAttempted QD = new QuizAlreadyAttempted();
                    QD.setVisible(true);
                    setVisible(false);
                    
                }
                else
                {
                    QuizNotAdded QN = new QuizNotAdded();
                    QN.setVisible(true);
                    setVisible(false);
                    
                    
                } 
             
            }
        }
        else
        {
            i=4;
            indexC=i-1;
           if(isAttempted()==0 && isAdded[SPChooseSubject.sIndexR][indexC]==true)
            {
                SPAttemptQuestion attemptQuestion = new SPAttemptQuestion();
                attemptQuestion.setVisible(true);
                setVisible(false);
            }
            else{
                if(isAttempted()==1)
                {
                    QuizAlreadyAttempted QD = new QuizAlreadyAttempted();
                    QD.setVisible(true);
                    setVisible(false);
                    
                }
                else
                {
                    QuizNotAdded QN = new QuizNotAdded();
                    QN.setVisible(true);
                    setVisible(false);
                    
                    
                } 
             
            }
        }
        /*SPAttemptQuestion attemptQuestion = new SPAttemptQuestion();
        attemptQuestion.setVisible(true);
        setVisible(false);*/
    }//GEN-LAST:event_btnQuiz1ActionPerformed

    private void btnQuiz3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuiz3ActionPerformed
        // TODO add your handling code here:
        if(checkSubject()==0)
        {
            i=3;
            indexC=i-1;
            if(isAttempted()==0 && isAdded[SPChooseSubject.sIndexR][indexC]==true)
            {
                SPAttemptQuestion attemptQuestion = new SPAttemptQuestion();
                attemptQuestion.setVisible(true);
                setVisible(false);
            }
            else{
                if(isAttempted()==1)
                {
                    QuizAlreadyAttempted QD = new QuizAlreadyAttempted();
                    QD.setVisible(true);
                    setVisible(false);
                    
                }
                else
                {
                    QuizNotAdded QN = new QuizNotAdded();
                    QN.setVisible(true);
                    setVisible(false);
                    
                    
                } 
             
            }
        }
        else
        {
            //System.out.println("quiz6");
            i=6;
            indexC=i-1;
            if(isAttempted()==0 && isAdded[SPChooseSubject.sIndexR][indexC]==true)
            {
                SPAttemptQuestion attemptQuestion = new SPAttemptQuestion();
                attemptQuestion.setVisible(true);
                setVisible(false);
            }
            else{
                if(isAttempted()==1)
                {
                    QuizAlreadyAttempted QD = new QuizAlreadyAttempted();
                    QD.setVisible(true);
                    setVisible(false);
                    
                }
                else
                {
                    QuizNotAdded QN = new QuizNotAdded();
                    QN.setVisible(true);
                    setVisible(false);
                    
                    
                } 
             
            }
        }
        /*SPAttemptQuestion attemptQuestion = new SPAttemptQuestion();
        attemptQuestion.setVisible(true);
        setVisible(false);*/
    }//GEN-LAST:event_btnQuiz3ActionPerformed

    private void lblBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBackActionPerformed
        // TODO add your handling code here:
        SPChooseSubject SCS = new SPChooseSubject();
        SCS.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_lblBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SPChooseQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SPChooseQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SPChooseQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPChooseQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SPChooseQuiz().setVisible(true);
                new SPChooseQuiz().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuiz1;
    private javax.swing.JButton btnQuiz2;
    private javax.swing.JButton btnQuiz3;
    private javax.swing.JButton lblBack;
    private javax.swing.JLabel lblQuiz;
    private javax.swing.JLabel lblStudentsPortal;
    // End of variables declaration//GEN-END:variables
}
