/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.quizms;

import static com.mycompany.quizms.GlobalClass.result;

/**
 *
 * @author User
 */
public class StudentSubjectScore extends javax.swing.JFrame {

    /**
     * Creates new form StudentCheckScore
     */
    public StudentSubjectScore() {
        initComponents();
        //System.out.println(StudentCheckScore.subject1);
        String b= StudentCheckScore.subject1;
        System.out.println(b);
        switch(b)
        {
            case "ODE":
                lblSubject.setText("ODE Score");
                break;
            case "OOP":
                lblSubject.setText("OOP Score");
                break;
        }
        String a=StudentCheckScore.subject1;
        //System.out.println(a);
        switch(a)
        {
            case "ODE":
                lblQuiz1.setText(result[Login.index][0]);
                lblQuiz2.setText(result[Login.index][1]);
                lblQuiz3.setText(result[Login.index][2]);
                break;
            case "OOP":
                lblQuiz1.setText(result[Login.index][3]);
                lblQuiz2.setText(result[Login.index][4]);
                lblQuiz3.setText(result[Login.index][5]);
                break;
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentsPortal = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblQ1 = new javax.swing.JLabel();
        lblQ3 = new javax.swing.JLabel();
        lblQ2 = new javax.swing.JLabel();
        lblT1 = new javax.swing.JLabel();
        lblT2 = new javax.swing.JLabel();
        lblT3 = new javax.swing.JLabel();
        lblObtained = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblQuiz1 = new javax.swing.JLabel();
        lblQuiz2 = new javax.swing.JLabel();
        lblQuiz3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Score");

        lblStudentsPortal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblStudentsPortal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentsPortal.setText("STUDENT  PORTAL");
        lblStudentsPortal.setToolTipText("");
        lblStudentsPortal.setName("lblStudentsPortal"); // NOI18N

        lblSubject.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblSubject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblQ1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQ1.setText("Quiz 1");
        lblQ1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblQ3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQ3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQ3.setText("Quiz 3");
        lblQ3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblQ2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQ2.setText("Quiz 2");
        lblQ2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblT1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblT1.setText("5");
        lblT1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblT2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblT2.setText("5");
        lblT2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblT3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblT3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblT3.setText("5");
        lblT3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblObtained.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblObtained.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObtained.setText("Obtained");
        lblObtained.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Total");
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblQuiz1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQuiz1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuiz1.setText("jLabel1");

        lblQuiz2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQuiz2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuiz2.setText("jLabel2");

        lblQuiz3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQuiz3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuiz3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblObtained, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblQuiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblQuiz2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblQuiz3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(83, 83, 83)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblT3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblT2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lblSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 257, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(lblStudentsPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblStudentsPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObtained, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lblQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblT3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuiz3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblT1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblT2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuiz2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(93, 93, 93)
                .addComponent(btnBack)
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        StudentCheckScore SCS = new StudentCheckScore();
        SCS.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSubjectScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSubjectScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSubjectScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSubjectScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentSubjectScore().setVisible(true);
                new StudentSubjectScore().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblObtained;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ2;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblQuiz1;
    private javax.swing.JLabel lblQuiz2;
    private javax.swing.JLabel lblQuiz3;
    private javax.swing.JLabel lblStudentsPortal;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblT1;
    private javax.swing.JLabel lblT2;
    private javax.swing.JLabel lblT3;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
