/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.quizms;

import static com.mycompany.quizms.GlobalClass.result;
import static com.mycompany.quizms.Login.tIndexR;

/**
 *
 * @author HP
 */
public class TPCheckScore extends javax.swing.JFrame {

    /**
     * Creates new form CheckScore
     */
    public TPCheckScore() {
        initComponents();
         switch(Login.subject)
        {
            case "ODE":
                lblSubject.setText("ODE Score");
                break;
            case "OOP":
                lblSubject.setText("OOP Score");
                break;
        }
        switch(tIndexR)
        {
            case 0:
                lblS1Q1.setText(result[0][0]);
                lblS1Q2.setText(result[0][1]);
                lblS1Q3.setText(result[0][2]);
                lblS2Q1.setText(result[1][0]);
                lblS2Q2.setText(result[1][1]);
                lblS2Q3.setText(result[1][2]);
                lblS3Q1.setText(result[2][0]);
                lblS3Q2.setText(result[2][1]);
                lblS3Q3.setText(result[2][2]);
                break;
            case 1:
                lblS1Q1.setText(result[0][3]);
                lblS1Q2.setText(result[0][4]);
                lblS1Q3.setText(result[0][5]);
                lblS2Q1.setText(result[1][3]);
                lblS2Q2.setText(result[1][4]);
                lblS2Q3.setText(result[1][5]);
                lblS3Q1.setText(result[2][3]);
                lblS3Q2.setText(result[2][4]);
                lblS3Q3.setText(result[2][5]);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTeachersPortal = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        lblS1 = new javax.swing.JLabel();
        lblS2 = new javax.swing.JLabel();
        lblS3 = new javax.swing.JLabel();
        lblQ1 = new javax.swing.JLabel();
        lblQ2 = new javax.swing.JLabel();
        lblQ3 = new javax.swing.JLabel();
        lblS2Q2 = new javax.swing.JLabel();
        lblS1Q1 = new javax.swing.JLabel();
        lblS2Q1 = new javax.swing.JLabel();
        lblS3Q3 = new javax.swing.JLabel();
        lblS3Q2 = new javax.swing.JLabel();
        lblS1Q2 = new javax.swing.JLabel();
        lblS1Q3 = new javax.swing.JLabel();
        lblS2Q3 = new javax.swing.JLabel();
        lblS3Q1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Score Check");
        setPreferredSize(new java.awt.Dimension(1017, 100));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTeachersPortal.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTeachersPortal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeachersPortal.setText("TEACHER PORTAL");

        lblSubject.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblSubject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubject.setText("ODE Score");

        lblS1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS1.setText("Saman");

        lblS2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblS2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS2.setText("Fatima");

        lblS3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblS3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS3.setText("Mishal");

        lblQ1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQ1.setText("Quiz 1");

        lblQ2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQ2.setText("Quiz 2");

        lblQ3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQ3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQ3.setText("Quiz 3");

        lblS2Q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS2Q2.setText("jLabel1");

        lblS1Q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS1Q1.setText("jLabel1");

        lblS2Q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS2Q1.setText("jLabel1");

        lblS3Q3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS3Q3.setText("jLabel1");

        lblS3Q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS3Q2.setText("jLabel1");

        lblS1Q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS1Q2.setText("jLabel1");

        lblS1Q3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS1Q3.setText("jLabel1");

        lblS2Q3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS2Q3.setText("jLabel1");

        lblS3Q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS3Q1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblS1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(lblS3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(lblS2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblS2Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblS1Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblS3Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblS1Q2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(lblS2Q2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(lblQ2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(lblS3Q2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblS3Q3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblS2Q3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(309, 309, 309))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblS1Q3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(309, 309, 309))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(lblQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(lblTeachersPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(lblSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblTeachersPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblS1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblS1Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblS1Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblS1Q3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblS2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblS2Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblS2Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblS2Q3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblS3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblS3Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblS3Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblS3Q3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        TeacherPortal TP = new TeacherPortal();
        TP.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPCheckScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPCheckScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPCheckScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPCheckScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPCheckScore().setVisible(true);
                new TPCheckScore().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ2;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblS1;
    private javax.swing.JLabel lblS1Q1;
    private javax.swing.JLabel lblS1Q2;
    private javax.swing.JLabel lblS1Q3;
    private javax.swing.JLabel lblS2;
    private javax.swing.JLabel lblS2Q1;
    private javax.swing.JLabel lblS2Q2;
    private javax.swing.JLabel lblS2Q3;
    private javax.swing.JLabel lblS3;
    private javax.swing.JLabel lblS3Q1;
    private javax.swing.JLabel lblS3Q2;
    private javax.swing.JLabel lblS3Q3;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTeachersPortal;
    // End of variables declaration//GEN-END:variables
}
